'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),cp=require('node:child_process');
const budgets=require('./budgets.json'),root=path.resolve(__dirname,'../..');
const digest=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function entries(dir,base=dir){return fs.readdirSync(dir).sort().flatMap(name=>{const file=path.join(dir,name),stat=fs.lstatSync(file);if(stat.isSymbolicLink())throw Error('Symlink in public artifact');return stat.isDirectory()?entries(file,base):[{path:path.relative(base,file).split(path.sep).join('/'),bytes:fs.readFileSync(file)}];});}
function manifest(dir){const files=Object.fromEntries(entries(dir).map(x=>[x.path,{sha256:digest(x.bytes),raw:x.bytes.length,gzip:zlib.gzipSync(x.bytes).length}]));return {files,artifactDigest:digest(JSON.stringify(files))};}
function checkSize(dir){const m=manifest(dir),rows=[];for(const route of budgets.routes){const file=route+'.html',html=fs.readFileSync(path.join(dir,file),'utf8'),svg=html.match(/<svg class="space-fallback"[\s\S]*?<\/svg>/)?.[0];if(!svg)throw Error('Missing static fallback '+route);const nodes=(svg.match(/<[a-z][\w-]*(?:\s|>)/gi)||[]).length;if(m.files[file].raw>budgets.htmlRawBytes||nodes>budgets.svgElements)throw Error('Size budget '+route);const assets=['styles.css','theme.js','space.js',...(route==='writing'?['archive.js']:[]),'assets/favicon.svg',...(route==='index'?['assets/vitalii-oborskyi-cutout.webp']:[])];const transfer=m.files[file].gzip+assets.reduce((n,f)=>n+m.files[f].gzip,0);if(transfer>budgets.routeGzipBytes)throw Error('Route transfer '+route);rows.push({route,...m.files[file],svgNodes:nodes,totalGzipBytes:transfer});}for(const [file,info]of Object.entries(m.files))if(!file.endsWith('.html')&&info.raw>budgets.assetRawBytes)throw Error('Asset size '+file);return {schema:1,kind:'sizes',pass:true,...m,rows};}
function git(arg){const r=cp.spawnSync('git',arg,{cwd:root,encoding:'utf8'});if(r.status!==0)throw Error(r.stderr);return r.stdout.trim();}
function build(out){fs.mkdirSync(out,{recursive:true});const target=path.join(out,'public');fs.rmSync(target,{recursive:true,force:true});fs.cpSync(path.join(root,'docs'),target,{recursive:true});const m={schema:1,sourceCommit:git(['rev-parse','HEAD']),sourceDirty:git(['status','--porcelain'])!=='',sourceTree:git(['rev-parse','HEAD^{tree}']),candidateCommit:process.env.SITE_CANDIDATE_SHA||git(['rev-parse','HEAD']),...manifest(target)};if(process.env.CI&&m.sourceDirty)throw Error('CI source must be clean');fs.writeFileSync(path.join(out,'artifact.json'),JSON.stringify(m,null,2)+'\n');fs.writeFileSync(path.join(out,'sizes.json'),JSON.stringify(checkSize(target),null,2)+'\n');return m;}
function verify(dir,record){const actual=manifest(dir);if(process.env.SITE_EXPECTED_PUBLIC_DIGEST&&actual.artifactDigest!==process.env.SITE_EXPECTED_PUBLIC_DIGEST)throw Error('Public digest differs from trusted build output');if(actual.artifactDigest!==record.artifactDigest||JSON.stringify(actual.files)!==JSON.stringify(record.files))throw Error('Artifact bytes do not match tested manifest');return true;}
if(require.main===module){const mode=process.argv[2],dir=process.argv[3];if(mode==='build')console.log(build(path.resolve(dir)));else if(mode==='sizes')console.log(checkSize(path.resolve(dir)));else if(mode==='verify')verify(path.resolve(dir),JSON.parse(fs.readFileSync(process.argv[4])));else throw Error('Usage: artifact.cjs build OUT | sizes DIR | verify DIR MANIFEST');}
module.exports={manifest,checkSize,build,verify,digest,entries};
